---
title: "Leaflet Mapping"
author: "Y.W"
date: "2018/9/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r message = FALSE,eval=FALSE}
rm(list = ls())
gc()
```
#Points on the map
```{r}
library(data.table)
#Display location on the map
pu_latlong <- fread("/Users/yang/Documents/Project - Group/Coordinates Document/pu_latlong.csv")
#Export data for QGIS
mfc<-fread("/Users/yang/Documents/Project - Group/Coordinates Document/mfc.csv")
mfp<-fread("/Users/yang/Documents/Project - Group/Coordinates Document/mfp.csv")


do_latlong <- na.omit(fread("/Users/yang/Documents/Project - Group/Coordinates Document/do_latlong.csv"))
names(pu_latlong)<- c("street","lon","lat")
names(do_latlong)<- c("street","lon","lat")

```

```{r}
library(leaflet.extras)
```

Method 1
```{r}
library(raster)                                  ##Load the Raster 
spain<-getData('GADM', country='ESP', level=4)  ##Get the Province Shapefile for France
```
```{r}
names(spain)
unique(spain$NAME_2)
barcelona<-subset(spain,NAME_4=="Barcelona")
province_barcelona<-subset(spain,NAME_2=="Barcelona")
plot(province_barcelona)
```
```{r}
leaflet(data =mfc)%>%
  addProviderTiles(providers$OpenStreetMap)%>%
  setView(lng=2.1783915,lat=41.39090,zoom = 11)%>%
  addPolygons(data = barcelona,weight =  5,col ='red',popup=~NAME_3,fillColor=heat.colors(4,alpha=1),stroke=FALSE)%>%
  addMarkers(clusterOptions = markerClusterOptions(),popup = ~htmlEscape(DO_street))%>%
  addWebGLHeatmap(size=600)
```


#Heat map
```{r}
#Build a function of Heatmap based on GADM
heatMap <-function(data,shape=NULL,col="blue",main="Sample HeatMap"){
  # Plots a Heat Map of a Polygons Data Frame.  This will 
    # demonstrate density within a finite set of polygons
    #
    # Args:
    #   data:   Spatial Points dataframe
    #   shape:  Polygons Data Frame 
    #
    #
    #   Notes:  This function requires the sp and RColorBrewer
    #           Packages
    #
    #   Beskow: 03/28/11   
    #
    is.installed <- function(mypkg) is.element(mypkg, 
                installed.packages()[,1])
    if (is.installed(mypkg="sp")==FALSE)  {
        stop("sp package is not installed")}
    if (is.installed(mypkg="RColorBrewer")==FALSE)  {
        stop("RColorBrewer package is not installed")}
    if (!class(data)=="SpatialPointsDataFrame")  {
        stop("data argument is not SpatialPointsDataFrame")}
require(sp)
require(RColorBrewer)
freq_table<-data.frame(tabulate(over(as(data,"SpatialPoints"),
    as(shape,"SpatialPolygons")),nbins=length(shape)))
names(freq_table)<-"counts"

shape1<-spChFIDs(shape,as.character(1:length(shape)))
row.names(as(shape1,"data.frame"))
spdf<-SpatialPolygonsDataFrame(shape1, freq_table, match.ID = TRUE)

rw.colors<-colorRampPalette(c("white",col))
spplot(spdf,scales = list(draw = TRUE),
        col.regions=rw.colors(max(freq_table)), main=main)
}
```

```{r}
library(sp)
library(RColorBrewer)
do<-mfc     ##create a new object that we will coerce to a SpatialPointsDataFrame
do<-do[!is.na(do$lat),]   ##Get rid of all NA's in the location field
coordinates(do)<-c("lon","lat")       ##Assigning coordinates coerces this to a SpatialPointsDataFrame
proj4string(do)<-proj4string(province_barcelona)   ##Assigns the texas spatial datum to our new data frame
```
```{r}
class(do)  #Prints the class of an object
```
```{r}
heatMap(do,province_barcelona,col = cm.colors(12),main="Restaurants Denstiy")
```

#Rworldmap
```{r}
library(readr)
overseastudent<-read.xlsx("/Users/yang/Documents/R studio/figure-12.xlsx")
setDT(overseastudent)
overseastudent2 <- overseastudent[!(1:12),]
names(overseastudent2)<-c("country","country_of_HE_provider","Year_Markers","Academic_Year","StudentCount")
Allyear <- overseastudent2[Year_Markers == "All",][country_of_HE_provider == "All"][order(-country)]

XVII_year <- Allyear[Academic_Year == "2016/17"
                     ][order(-StudentCount)]
str(XVII_year)
unique(Allyear$country)
```

##Ggplot
```{r}
library(ggplot2)
XVII_year_TOP10 <- XVII_year[(1:10),]
setDT(XVII_year_TOP10)
ggplot(XVII_year_TOP10, aes(reorder(country,StudentCount), StudentCount)) +
  geom_bar( stat = "identity",color='tomato',fill = 'skyblue') +
  theme(axis.text.x=element_text(angle =90,hjust = 1,vjust = 1))+
  coord_flip()
```



Filter ggplot line graph
```{r}
Allyear %>%
  filter(country %in% c("Malaysia", "United States", "India","Nigeria","Hong Kong  Special Administrative Region of China ","Saudi Arabia")) %>%
  ggplot(aes(x=Academic_Year, y = StudentCount, group = country,color = country)) + 
  geom_line() + geom_point()
```





##World map
```{r}
library(rworldmap)
```

```{r}
XVII_map <- joinCountryData2Map(XVII_year,joinCode = "NAME",nameJoinColumn = "country")
mapDevice()
XVII_map2<-mapCountryData(XVII_map,nameColumnToPlot='StudentCount', 
               addLegend = FALSE,
               colourPalette = "diverging",
               mapTitle = "2016/17 Overseas Students in UK")
do.call(addMapLegend
       ,c(XVII_map2
         ,legendLabels="all"
         ,legendWidth=0.5
         ,legendIntervals="data"
         ,legendMar = 2))
```




